# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
    following.twig_extension:
        class: FrontendBundle\Twig\FollowingExtension
        public: false
        arguments:
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }

    long_time.twig_extension:
        class: FrontendBundle\Twig\LongTimeExtension
        public: false
        tags:
            - { name: twig.extension }

    liked.twig_extension:
        class: FrontendBundle\Twig\LikedExtension
        public: false
        arguments:
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }

    user_stats.twig_extension:
        class: FrontendBundle\Twig\UserStatsExtension
        public: false
        arguments:
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }

    get_user.twig_extension:
        class: FrontendBundle\Twig\GetUserExtension
        public: false
        arguments:
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }

    app.notification_service:
        class: FrontendBundle\Services\NotificationService
        arguments: ["@doctrine.orm.entity_manager"]
