following_follow:
  path: /follow
  defaults: { _controller: FrontendBundle:Following:follow }
  methods: [POST]

following_unfollow:
  path: /unfollow
  defaults: { _controller: FrontendBundle:Following:unfollow }
  methods: [POST]