private_message_index:
  path: /private-message
  defaults: { _controller: FrontendBundle:PrivateMessage:index }

private_message_sended:
  path: /private-message/sended
  defaults: { _controller: FrontendBundle:PrivateMessage:sended }