home_publications:
  path: /home
  defaults: { _controller: FrontendBundle:Publication:index }

remove_publications:
  path: /publication/remove/{id}
  defaults: { _controller: FrontendBundle:Publication:removePublication }
