login:
  path: /login
  defaults: { _controller: FrontendBundle:User:login }

register:
  path: /register
  defaults: { _controller: FrontendBundle:User:register }

user_nick_test:
  path: /nick-test
  defaults: { _controller: FrontendBundle:User:nickTest }
  methods: [POST]
