login:
  path: /login
  defaults: { _controller: FrontendBundle:User:login }

login_check:
  path: /login_check

logout:
  path: /logout

register:
  path: /register
  defaults: { _controller: FrontendBundle:User:register }

user_nick_test:
  path: /nick-test
  defaults: { _controller: FrontendBundle:User:nickTest }
  methods: [POST]

edit_user:
  path: /my-data
  defaults: { _controller: FrontendBundle:User:editUser }

user_list:
  path: /people
  defaults: { _controller: FrontendBundle:User:users }

user_search:
  path: /search
  defaults: { _controller: FrontendBundle:User:search }

user_profile:
  path: /user/{nickname}
  defaults: { _controller: FrontendBundle:User:profile, nickname:null }