app_user:
  resource: "@FrontendBundle/Resources/config/routing/user.yml"
  prefix: /

app_publication:
  resource: "@FrontendBundle/Resources/config/routing/publication.yml"
  prefix: /

app_follows:
  resource: "@FrontendBundle/Resources/config/routing/following.yml"
  prefix: /

app_like:
  resource: "@FrontendBundle/Resources/config/routing/like.yml"
  prefix: /

app_notifications:
  resource: "@FrontendBundle/Resources/config/routing/notification.yml"
  prefix: /

frontend_homepage:
  path:     /
  defaults: { _controller: FrontendBundle:Default:index }
